### ISSUE TITLE
Kalman Filter: Likelihood

### ISSUE THREAD

**Issue by cc7768** [ElOceanografo/StateSpace.jl#1]
Hi.  This seems like a neat package and I found the idea of tracking the distributions as opposed to just the mean and variance a clever idea.  I have been perusing for the last couple days and I think there are a couple things that might be bugs

Firstly, I was wondering about how you were computing the likelihood.  I am slightly confused as to why you were adding two different things to the likelihood inside the Kalman filter in lines [86](https://github.com/ElOceanografo/StateSpace.jl/blob/master/src/KalmanFilter.jl#L86) and [89](https://github.com/ElOceanografo/StateSpace.jl/blob/master/src/KalmanFilter.jl#L89).  I think typically the Kalman filter decomposes the likelihood into

prob(y^T | x_0) = prob(y_1 | x_0) prob(y_2 | y_1) prob(y_3 | y_2) ... prob(y_t | y_{t-1})

so I don't understand what line 86 adds.  It could be that it is equivalent and I just don't see it.

Secondly, I think that the distribution that you are computing in `observe` is slightly off.  I believe the variance should be `m.G * cov(x) * m.G' + m.W` instead of `m.W`.

**Comment by ElOceanografo** [comment]
Nine months later...

I checked, and the likelihood is correct as written: it is the product of the probability of going from x(t-1) to x(t), and the probability of observing y(t) given x(t).  This is laid out conceptually in section 8.1.1 of Cressie and Wikle, "Statistics for Spatio-Temporal Data."
